version: "3"

services:
  webcam:
    image: webcam
    container_name: webcam
    build:
      context: .
    environment:
      - DISPLAY=unix$DISPLAY
    devices:
      - /dev/video1:/dev/video0

    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
