version: "3"

services:
  webcam:
    image: webcam
    container_name: webcam
    working_dir: /webcam
    build:
      context: .
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - ./:/webcam
      - /dev/video0:/dev/video0
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: bash -c "nvidia-smi && python -u camera.py"
    privileged: true
    runtime: nvidia
